[package]
name = "quantum-sim"
version = "0.1.0"
authors = ["Cl√°udio Gomes <cfpgcp3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.24"
num-complex = "0.3.1"
num = "0.1.27"